### ISSUE TITLE
[question] internationalisation

### ISSUE THREAD

**Issue by Thomas131** [kawaii/mybb-amnesia#17]
Hello!
A german Forum I am responsible for will use this plugin and I wanted to ask if there are plans to add translation. I would be glad to provide the informal german translation (deutsch_du). (In fact, I am already working on it because I need it for my forum)

Best Regards!
Thomas

**Comment by SvePu** [comment]
You can download the German translation files from here:
https://github.com/SvePu/mybb-amnesia-german-translation-files

**Comment by Thomas131** [comment]
Thank you very much!

**Comment by SvePu** [comment]
You're welcome!
