### ISSUE TITLE
Issue when doing data export

### ISSUE THREAD

**Issue by mallic** [kawaii/mybb-amnesia#3]
Tried testing the data export function and got the following issue with one of the custom profile fields on export. Running MYBB 1.8.15 and PHP 7.1.9

Fatal error: Uncaught DOMException: Invalid Character Error in D:\non_game_servers\wamp\www\devildogs\inc\plugins\amnesia\core_portability.php:300 Stack trace: #0 D:\non_game_servers\wamp\www\devildogs\inc\plugins\amnesia\core_portability.php(300): DOMDocument->createElement('Main Callsign') #1 D:\non_game_servers\wamp\www\devildogs\inc\plugins\amnesia\core_portability.php(305): amnesia\appendArrayToXmlElement(Array, Object(DOMDocument), Object(DOMElement)) #2 D:\non_game_servers\wamp\www\devildogs\inc\plugins\amnesia\core_portability.php(194): amnesia\appendArrayToXmlElement(Array, Object(DOMDocument), Object(DOMElement)) #3 D:\non_game_servers\wamp\www\devildogs\inc\plugins\amnesia\hooks_frontend.php(239): amnesia\outputUserPersonalDataXml(1, true) #4 D:\non_game_servers\wamp\www\devildogs\inc\class_plugins.php(142): amnesia\Hooks\usercp_start('') #5 D:\non_game_servers\wamp\www\devildogs\usercp.php(57): pluginSystem->run_hooks(Array) #6 {main} thrown in D:\non_game_servers\wamp\www\devildogs\inc\plugins\amnesia\core_portability.php on line 300

Not sure why it is complaining about invalid character. This is a plain text profile field.

**Comment by kawaii** [comment]
Thank you for the report, we'll look into this soon.
