### ISSUE TITLE
Users in a banned group cannot use data erasure or pull request form

### ISSUE THREAD

**Issue by mallic** [kawaii/mybb-amnesia#5]
Title of issue explains it all. I may be wrong, but I feel like international courts will not accept the user as being banned for a reason of being unable to pull their data. And banning a user does not remove their data from the site inherently.

**Comment by dvz** [comment]
This appears to be overlapping with imperfections in MyBB (e.g. the _Change Password/Email_,  _Contact Us_ pages, etc. not being available for banned users). It might be possible to fix it indirectly (essentially tricking MyBB to allow certain pages) but we'd also need to display the URLs on the lockout page (same with UCP sections that should be available).

**Comment by andrewjs18** [comment]
I personally cannot duplicate this...it seems to work as expected for me on a test board with no other plugins installed.

**Comment by chack1172** [comment]
I don't think we should try to allow banned users to use the data erasure or date export. They can use the contact.php page to ask for it and then an administrator can do it from ACP, so we should add an option an ACP to do that. This is my opinion.
