### ISSUE TITLE
Users cannot logout after submitting a erasure request.

### ISSUE THREAD

**Issue by mallic** [kawaii/mybb-amnesia#6]
Created a test user and made some posts to test erasing a user. I asked to have the account erased and I then could not log out of the forums, as every time I hit logout, the plugin redirected me to the page saying my erasure is pending acceptance by an admin. To log out, I had to clear my data in firefox for the past hour. Not sure if you want to fix it, but I am reporting it.

**Comment by Eldenroot** [comment]
How to update without losing data? Just deactivate -> copy new files -> activate? Thank you

**Comment by dvz** [comment]
Yes; in case of template changes (if any, in the future) the plugin should be deactivated, overwritten and activated again.
